### PR TITLE
Bootstrap 4 for Joomla 4.x

### PR DESCRIPTION
**Pull request by 4digitalworld**
Since Joomla 3.5 support PHP 7, i think this is right way for support new technologies.
I'm read, Joomla 4.0 coming soon later this year:
http://magazine.joomla.org/issues/issue-december-2015/item/2911-introducing-joomla-4

just skip Bootstrap 3.x and put Bootstrap 4 support into Joomla 4.x

i think this is no big problem just rename some words in CSS code for compatibility with Bootstrap 4.

to follow new technologies, it is the only right way.

http://v4-alpha.getbootstrap.com/
https://github.com/twbs/bootstrap/tree/v4-dev

just follow this comment https://github.com/joomla/joomla-cms/pull/9907#issuecomment-209857687

### CODE REVIEW

**Comment by nibra** [comment]
As Joomla!4 will support different Renderers, Bootstrap 4 support is no problem at all. If it should not be part of the first release, it can be added any time later (4.x), thanks to the new architecture.

As the code of this PR is not related to the comment (you better had created an issue on the tracker), it is closed.

**Comment by Bakual** [comment]
> As Joomla!4 will support different Renderers, Bootstrap 4 support is no problem at all. If it should not be part of the first release, it can be added any time later (4.x), thanks to the new architecture.

Personally I think Bootstrap 4 isn't about rendering. It's about the flavour of the default HTML output we use. I see it as our "standardised UI" if you want to call it so. That's the big advantage Bootstrap 2 had in Joomla 3 which allowed the various extensions to match much much better into any Bootstrap supporting template.
It also allows 3rd party extensions to use commong JS stuff (tabs, slider, tooltip/popover, ...) without inventing/including it every time themself, also giving a "standardised" HTML output.

So Joomla 4 allowing different renderers is cool, but we still need our "standard UI" thing to follow, which imho indeed should be Bootstrap 4. Call it our default renderer or whatever.

**Comment by 4digitalworld** [comment]
@Bakual i agree with you

@nibra Joomla 4.x really need "standardised UI" for developers, who don't worry about design of their apps for Joomla.

**Comment by HermanPeeren** [comment]
Please look at the 'clean base' branch under libraries/incubator what is meant with a Renderer in Joomla-4:
https://github.com/joomla-projects/joomla-pythagoras/tree/clean-base/libraries/incubator/Renderer

You'll see that a Renderer is not even necessarily meant to render to HTML. The idea is that a Content Tree can be rendered in totally different ways: as HTML, as PDF, as JSON, whatever. All from the same Content Tree. An extension will produce a Content Tree, which consists of instantiations of Content Types. If the developer uses pre-defined Content Types, then a renderer for it exists and the developer doesn't have to worry about rendering. If the developer wants to use a custom Content Type, then some plugin-or-something-similar for the Renderer(s) has to be provided in order to render the custom Content Type.

**Comment by 4digitalworld** [comment]
@HermanPeeren this is good with "HTML, PDF, JSON, etc"

but i think, Joomla need replace "Bootstrap 2" on "Bootstrap 4" for users who want renderer like on Joomla 3.x

i mean, just put into Joomla 4.x render via "Bootstrap 4" for html pages for easy move from Joomla 3.x to Joomla 4.x

**Comment by HermanPeeren** [comment]
Most probably there will be such a Bootstrap 4 (or later) Renderer by the time Joomla 4 is released. Obvious and no problem. As Niels said: "As Joomla!4 will support different Renderers, Bootstrap 4 support is no problem at all". It is a minor point once the idea of adding an intermediate layer (Content Tree) is realised.

**Comment by 4digitalworld** [comment]
@HermanPeeren good to hear it!

i'm create this thread here - https://github.com/joomla-projects/joomla-pythagoras/issues/82
please no closed, because this idea want many people!

**Comment by HermanPeeren** [comment]
We had a lot of problems being stuck with Bootstrap 2 as our default HTML-UI-framework. If you wanted to use an extension in a template based on another framework (like Bootstrap 3 or something else). You always had to make template overrides then. 

Now say we use Bootstrap X as default when Joomla 4 comes out. Then, half a year later Bootstrap Y or SuperHandyNewAndShiny 1.0  suddenly is the most used UI-framework. In the current J!3-scenario you'll have to make new overrides for all extensions. In the new scenario you add a new Renderer and don't have to change anything at the extensions (except maybe providing some plugin-like rendering of custom Content Types). 

The idea is to make it simpler by putting things together that belong together. Rendering for a specific UI-framework should not be a concern for an extension.

**Comment by Bakual** [comment]
> We had a lot of problems being stuck with Bootstrap 2 as our default HTML-UI-framework.

Depends who you ask. Imho, the problems weren't a lot, and they were (almost) all solvable with overrides. Which btw are a perfectly fine solution.

> In the new scenario you add a new Renderer and don't have to change anything at the extensions (except maybe providing some plugin-like rendering of custom Content Types).

I have to see it first how that works, but I guess most 3rd party extension will be "custom" content types and thus they need to provide "plugins" for rendering. And I fear the day I as extension developer have to provide such renderers for BS4, BS5, whatever is there. Personally I will stick to one renderer/output for sure, and this will be the default one Joomla ships with.

**Comment by HermanPeeren** [comment]
Let's stop discussing this at two places and continue our conversation at #82. I appreciate your concerns very much! Keep on asking questions and being concerned about how this works, for it will challenge dreamers (like me) to sharper define and develop the vision.

**Pull request closed without merging**
