### PR TITLE
Removed JAdministratorHelper

### PR DESCRIPTION
**Pull request by laoneo**

### CODE REVIEW

**Comment by mbabker** [comment]
Add a pull request to the `3.5-dev` branch on the main CMS repo deprecating the class there and I think we're good to go.

**Comment by laoneo** [comment]
Added PR https://github.com/joomla/joomla-cms/pull/8075.

**Comment by Hackwar** [comment]
What is stopping us from merging this one?

**Comment by nibra** [comment]
It does not need to be merged here, since it was merged in `joomla/joomla-cms:3.5-dev`. Thus it will be incorporated automatically. @laoneo: If I'm not wrong, please close this.

**Comment by Hackwar** [comment]
The class was only deprecated in 3.5, not removed. This still needs to be merged.

**Comment by laoneo** [comment]
Yes it needs to be merged.

**Pull request merged**
