### PR TITLE
Command Line Interface

### PR DESCRIPTION
**Pull request by nibra**
This PR adds a command line interface. It is work in progress. To invoke it, just type

``` bash
$ ./joomla list
```

to see a list of available commands.

Fixes Issue #118. This PR includes #117.

### CODE REVIEW

**Comment by fastslack** [comment]
@nibra Do you have any step by step for testing? im using your branch directly and receive this:

```
$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
  - Installing sebastian/resource-operations (1.0.0)
    Loading from cache

  - Installing sebastian/object-enumerator (1.0.0)
    Loading from cache

  - Removing phpunit/phpunit-mock-objects (2.3.8)
  - Installing phpunit/phpunit-mock-objects (3.2.3)
    Downloading: 100%

  - Installing sebastian/code-unit-reverse-lookup (1.0.0)
    Loading from cache

  - Removing phpunit/php-code-coverage (2.2.4)
  - Installing phpunit/php-code-coverage (4.0.0)
    Downloading: 100%

  - Installing myclabs/deep-copy (1.5.1)
    Loading from cache

  - Removing phpunit/phpunit (4.8.26)
  - Installing phpunit/phpunit (5.4.3)
    Downloading: 100%

  - Installing nikic/php-parser (v0.9.5)
    Downloading: 100%

  - Installing jeremeamia/superclosure (1.0.2)
    Downloading: 100%

Generating autoload files

$ ./joomla
PHP Fatal error:  Uncaught Error: Class 'Joomla\DI\Container' not found in /home/fastslack/mtwProjects/joomla-pythagoras/init.php:20
Stack trace:
#0 /home/fastslack/mtwProjects/joomla-pythagoras/joomla(37): initContainer()
#1 {main}
  thrown in /home/fastslack/mtwProjects/joomla-pythagoras/init.php on line 20
```

**Comment by fastslack** [comment]
@nibra After cleanup repo, i installed everything ok. localhost:8080 seems to works fine.

```
$ ./libraries/vendor/bin/robo test
 [FileSystem\FilesystemStack] mkdir ["build\/reports"]
➜  Creating test database in /home/fastslack/mtwProjects/joomla-pythagoras.nibra/tests/unit/ORM/data/original/sqlite.test.db
➜  Creating table articles
➜  Adding 4 records
➜  Creating table details
➜  Adding 5 records
➜  Creating table extras
➜  Adding 3 records
➜  Creating table maps
➜  Adding 12 records
➜  Creating table masters
➜  Adding 5 records
➜  Creating table tags
➜  Adding 3 records
➜  Creating table users
➜  Adding 3 records
➜  Creating test database in sqlite.test.db
 [FileSystem\FilesystemStack] copy ["\/home\/fastslack\/mtwProjects\/joomla-pythagoras.nibra\/tests\/unit\/ORM\/data\/original\/sqlite.test.db","\/home\/fastslack\/mtwProjects\/joomla-pythago
ras.nibra\/tests\/unit\/ORM\/data\/sqlite.test.db"]
 [FileSystem\FilesystemStack] remove ["\/home\/fastslack\/mtwProjects\/joomla-pythagoras.nibra\/tests\/unit\/ORM\/data\/articles.csv"]
 [FileSystem\FilesystemStack] copy ["\/home\/fastslack\/mtwProjects\/joomla-pythagoras.nibra\/tests\/unit\/ORM\/data\/original\/articles.csv","\/home\/fastslack\/mtwProjects\/joomla-pythagora
s.nibra\/tests\/unit\/ORM\/data\/articles.csv"]
 [FileSystem\FilesystemStack] remove ["\/home\/fastslack\/mtwProjects\/joomla-pythagoras.nibra\/tests\/unit\/ORM\/data\/details.csv"]
 [FileSystem\FilesystemStack] copy ["\/home\/fastslack\/mtwProjects\/joomla-pythagoras.nibra\/tests\/unit\/ORM\/data\/original\/details.csv","\/home\/fastslack\/mtwProjects\/joomla-pythagoras
.nibra\/tests\/unit\/ORM\/data\/details.csv"]
 [FileSystem\FilesystemStack] remove ["\/home\/fastslack\/mtwProjects\/joomla-pythagoras.nibra\/tests\/unit\/ORM\/data\/extras.csv"]
 [FileSystem\FilesystemStack] copy ["\/home\/fastslack\/mtwProjects\/joomla-pythagoras.nibra\/tests\/unit\/ORM\/data\/original\/extras.csv","\/home\/fastslack\/mtwProjects\/joomla-pythagoras.
nibra\/tests\/unit\/ORM\/data\/extras.csv"]
 [FileSystem\FilesystemStack] remove ["\/home\/fastslack\/mtwProjects\/joomla-pythagoras.nibra\/tests\/unit\/ORM\/data\/maps.csv"]
 [FileSystem\FilesystemStack] copy ["\/home\/fastslack\/mtwProjects\/joomla-pythagoras.nibra\/tests\/unit\/ORM\/data\/original\/maps.csv","\/home\/fastslack\/mtwProjects\/joomla-pythagoras.ni
bra\/tests\/unit\/ORM\/data\/maps.csv"]
 [FileSystem\FilesystemStack] remove ["\/home\/fastslack\/mtwProjects\/joomla-pythagoras.nibra\/tests\/unit\/ORM\/data\/masters.csv"]
 [FileSystem\FilesystemStack] copy ["\/home\/fastslack\/mtwProjects\/joomla-pythagoras.nibra\/tests\/unit\/ORM\/data\/original\/masters.csv","\/home\/fastslack\/mtwProjects\/joomla-pythagoras
.nibra\/tests\/unit\/ORM\/data\/masters.csv"]
 [FileSystem\FilesystemStack] remove ["\/home\/fastslack\/mtwProjects\/joomla-pythagoras.nibra\/tests\/unit\/ORM\/data\/tags.csv"]
 [FileSystem\FilesystemStack] copy ["\/home\/fastslack\/mtwProjects\/joomla-pythagoras.nibra\/tests\/unit\/ORM\/data\/original\/tags.csv","\/home\/fastslack\/mtwProjects\/joomla-pythagoras.ni
bra\/tests\/unit\/ORM\/data\/tags.csv"]
 [FileSystem\FilesystemStack] remove ["\/home\/fastslack\/mtwProjects\/joomla-pythagoras.nibra\/tests\/unit\/ORM\/data\/users.csv"]
 [FileSystem\FilesystemStack] copy ["\/home\/fastslack\/mtwProjects\/joomla-pythagoras.nibra\/tests\/unit\/ORM\/data\/original\/users.csv","\/home\/fastslack\/mtwProjects\/joomla-pythagoras.n
ibra\/tests\/unit\/ORM\/data\/users.csv"]
 [Testing\Codecept] Executing /home/fastslack/mtwProjects/joomla-pythagoras.nibra/libraries/vendor/bin/codecept run -c codeception.yml --verbose
Codeception PHP Testing Framework v2.2.1
Powered by PHPUnit 5.4.3 by Sebastian Bergmann and contributors.

Acceptance Tests (0) ---------------------------------------------------------
Modules: PhpBrowser, \Helper\Acceptance
------------------------------------------------------------------------------
------------------------------------------------------------------------------

Unit Tests (448) -------------------------------------------------------------
Modules: Asserts, \Helper\Unit, Mockery
------------------------------------------------------------------------------
✔ RendererCest: Renderer adds the event decorator (0.0s)
{SNIP}
------------------------------------------------------------------------------

Api Tests (0) ----------------------------------------------------------------
Modules: \Helper\Api
------------------------------------------------------------------------------
------------------------------------------------------------------------------

Functional Tests (0) ---------------------------------------------------------
Modules: \Helper\Functional
------------------------------------------------------------------------------
------------------------------------------------------------------------------

Cli Tests (0) ----------------------------------------------------------------
Modules: \Helper\Cli
------------------------------------------------------------------------------
------------------------------------------------------------------------------


Time: 1.18 seconds, Memory: 22.00MB

There was 1 skipped test:

---------
1) UpperCaseListenerTest: Upper case listener compound
 Test  tests/unit/Extensions/Uppercase/Listener/UpperCaseListenerTest.php:testUpperCaseListenerCompound
Temporarily disabled

OK, but incomplete, skipped, or risky tests!
Tests: 448, Assertions: 803, Skipped: 1.
 [Testing\Codecept] Done in 1.236s
 [FileSystem\FilesystemStack] remove ["codeception.yml"]
```

Test fails on code style

```
$ ./libraries/vendor/bin/robo check:style
 [Exec] Running /home/fastslack/mtwProjects/joomla-pythagoras.nibra/libraries/vendor/bin/phpcs --standard=/home/fastslack/mtwProjects/joomla-pythagoras.nibra/libraries/vendor/greencape/coding
-standards/src/Joomla --ignore=build,cache,docs,logs,tests,tmp,libraries/vendor /home/fastslack/mtwProjects/joomla-pythagoras.nibra --report=full --report-checkstyle=build/reports/checkstyle.
xml

FILE: ...wProjects/joomla-pythagoras.nibra/templates/bootstrap4/index.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 4 WARNINGS AFFECTING 4 LINES
----------------------------------------------------------------------
 17 | WARNING | Line exceeds 150 characters; contains 218 characters
 18 | WARNING | Line exceeds 150 characters; contains 198 characters
 19 | WARNING | Line exceeds 150 characters; contains 202 characters
 20 | WARNING | Line exceeds 150 characters; contains 209 characters
----------------------------------------------------------------------


FILE: ...twProjects/joomla-pythagoras.nibra/layouts/bootstrap-3/image.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------
 1 | WARNING | A file should declare new symbols (classes, functions,
   |         | constants, etc.) and cause no other side effects, or
   |         | it should execute logic with side effects, but should
   |         | not do both. The first symbol is defined on line 19
   |         | and the first side effect is on line 34.
----------------------------------------------------------------------


FILE: ...twProjects/joomla-pythagoras.nibra/layouts/bootstrap-4/image.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------
 1 | WARNING | A file should declare new symbols (classes, functions,
   |         | constants, etc.) and cause no other side effects, or
   |         | it should execute logic with side effects, but should
   |         | not do both. The first symbol is defined on line 19
   |         | and the first side effect is on line 34.
----------------------------------------------------------------------


FILE: ...ck/mtwProjects/joomla-pythagoras.nibra/layouts/uikit-2/image.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------
 1 | WARNING | A file should declare new symbols (classes, functions,
   |         | constants, etc.) and cause no other side effects, or
   |         | it should execute logic with side effects, but should
   |         | not do both. The first symbol is defined on line 19
   |         | and the first side effect is on line 34.
----------------------------------------------------------------------

Time: 1.04 secs; Memory: 24Mb

 [Exec]  Exit code 1  Time 1.087s
 [Robo\Result] Stopping on fail. Exiting....
 [Robo\Result] Exit Code: 1
```

**Comment by nibra** [comment]
Am 16.09.2016 um 21:22 schrieb Matias Aguirre:

Sorry for being late regarding my answer - I was busy with the JoomlaDay
Germany this weekend.

> @nibra After cleanup repo, i installed everything ok. localhost:8080 seems to works fine.

So, I guess, your problem is solved so far, right?

Regards,
Niels

## 

| New Stars on the Horizon:      GreenCape  ·  nibralab  ·  laJoom |
| http://www.bsds.de   ·   BSDS Braczek Software- und DatenSysteme |
| Webdesign · Webhosting · e-Commerce · Joomla! Content Management |

---

**Comment by fastslack** [comment]
@nibra Yes, i sorted all issues about database port and docker stuff and everything is working fine :D

**Pull request merged**
