### PR TITLE
Refactored content types to be extensible

### PR DESCRIPTION
**Pull request by nibra**
For the seemless integration of horizontal components, the HCs need to have access to the output. The place to grant this with the least impact are the content types, that wrap entities.

### CODE REVIEW

**Comment by laoneo** [comment]
I don't understand, why are component specific content types added to the content package. From my understanding they should be part of the article (now named content) component.

**Comment by nibra** [comment]
They should be independent from specific components, so the can be re-used. The Article element, fx., allows _any_ component to render its content like an article.

**Comment by laoneo** [comment]
But then I would place it in the content (probably better name would be
article) component. When another component wants to render their entity as
article, then they should have a relation to the content/article component.
In my world the content items should be component independent, means they
should only contain basic items.

**Comment by nibra** [comment]
The article structure can be used by other components as well. It is in no way restricted to [com_]content.

Both Articles and Teasers are elements, that are (will be) defined independant of components in the pattern library, which is ment to cover all commonly used patterns. This allows component and template developers to work independantly.

**Comment by laoneo** [comment]
How should it then be used? If I have a download component I need to create an article content type?

**Comment by nibra** [comment]
No, you're encouraged to use the predefined elements, because the templates already cover them.You can build something totally different, if you need to, but then you're responsible for the 'inner' integration.

**Pull request closed without merging**
