### PR TITLE
Feature/pagebuilder

### PR DESCRIPTION
**Pull request by nibra**
## Initial Attempt to Produce Visible Output

This PR adds page handling. It uses the data structures of the `PageBuilder` (which's GUI still is to be created).
### Installation

The PR includes a primitive installer, that resolves relations between entities and builds up the database. The following command deletes the database and the compiled entity definitions, and rebuilds them:

``` bash
$ rm -f data/sqlite.db && rm -f data/entities/*.xml && php installation/install.php
```

This step is currently only needed before the first run, and when you manually add data records to the extensions.
### Run the Demo

The installation is designed to be run using `docker-compose`:

``` bash
$ docker-compose up -d
```

In your browser, head to `http://localhost:8080/index.php` and pick an item from the menu, or go to `http://localhost:8080/index.php/admin/pagebuilder` to see a (not yet functional) prototype of the PageBuilder.

However, currently only the `web` container is used, so you should be able to run the demo without `docker-compose`, if you have a web server installed and your source directory is accessible for it.
### Enitities and Elements

Since both are called `ContentTypes` from time to time, it is necessary to distinuish those two.
**Entities** mostly respond to database records. **Elements** are components of a page, and thus subject for layout and styling.

In this PR, you'll find basic elements, like image or headline, as well as 'active' elements, like slider or accordion. The `PageBuilder` itself delivers an example of a custom element, the `TemplateSelector`. It shows how you can compose your custom elements from the existing elements.

### CODE REVIEW

**Comment by fastslack** [comment]
@nibra After installed docker i tryed to run the demo and i had:

```
$ sudo docker-compose up -d
Pulling db (mysql:latest)...
latest: Pulling from library/mysql
357ea8c3d80b: Pull complete
256a92f57ae8: Pull complete
d5ee0325fe91: Pull complete
a15deb03758b: Pull complete
7b8a8ccc8d50: Pull complete
1a40eeae36e9: Pull complete
833539b56478: Pull complete
4f350efbb7e5: Pull complete
266f161e49c6: Pull complete
b53a75e45220: Pull complete
75196bb75c29: Pull complete
Digest: sha256:c8f03238ca1783d25af320877f063a36dbfce0daa56a7b4955e6c6e05ab5c70b
Status: Downloaded newer image for mysql:latest
Creating joomlapythagoras_db_1
ERROR: driver failed programming external connectivity on endpoint joomlapythagoras_db_1 (bd50fb5d3722b6629449134dff0e2be2eb5cd8bd9ac066d43238f3de9a9f0e45): Error starting userland proxy: listen tcp 0.0.0.0:3306: bind: address already in use
```

Where can i set another port to database?

**Comment by nibra** [comment]
You can change the port in the file `docker-compose.yml`:

``` yaml
db:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
  ports:
    - "3307:3306"
```

with `3307` being your new port number.

Alternatively, you can remove the `db`, `hub`, and `firefox` entries, as they are currently not used.

**Comment by nibra** [comment]
Addition of Joomla/Router closes #59

**Comment by nibra** [comment]
This PR is now included in (i.e., needed for) #122

**Pull request merged**
