### PR TITLE
Remove deprecated code

### PR DESCRIPTION
**Pull request by mbabker**
This branch addresses a majority of the deprecations for 4.0.

### CODE REVIEW

**Comment by mbabker** [comment]
Outdated, out of sync with project vision.  Closed.

**Comment by nibra** [comment]
> out of sync with project vision

Don't think, that's the case.
Please redo this PR against `joomla/joomla-cms`, so it can go into J!4.

**Comment by mbabker** [comment]
Well if your clean base approach goes through it doesn't matter anyway
because you've carried forward no code and inherently deprecated
everything.  So to me it's out of sync and not worth time or effort for
what's essentially documentation now.

**Comment by nibra** [comment]
If the clean-base approach gets accepted, it will stand as a lighthouse, defining the direction the incremental development will go. That's why Pythagoras was renamed to Joomla X, so the version number no longer stands in the way for that. So, this PR is not out of sync with the project vision; it is a step towards it.

**Comment by mbabker** [comment]
If this repository's purpose and the project's vision has changed yet again
then it needs to be documented better than in the PLT meeting notes.  This
repo started as an official working space for what was supposed to be a J4
as envisioned at JAB15 then derailed into what is at best right now an
experimental repository considering it is a clean base with no continuity
to any existing Joomla code (there isn't an issue in that itself, I've
tried that concept, but never tried to market as an official working
group's space nor do I feel now that a full deprecation of all existing
APIs in favor of a reimagined application is in the project's best
interests considering its history of being unable to handle "major"
increments in a smoothly upgradeable manner).  So for all intents and
purposes there once again isn't an official working space for a Joomla 4.0,
and to me any effort to rebase this almost 8 month old branch into
something salvageable for a 4.0 branch if one is ever truly created and
followed through on, which to be frank somewhere near the end of my PLT run
almost 2 years ago I had it decided that the project would never release
because overall software planning and road mapping has never existed here
and any effort to move forward on it would stall.  Since JAB15 that's
happened at least twice.

To be clear I've never been against this initiative at face value.  But, I
frankly do not see a future for Joomla that involves forcing every one of
the existing tens of thousands of extensions being rewritten as a positive
future nor do I feel that architecturally starting from scratch then trying
to figure out how to work existing APIs into the new structure either as
proxies or a legacy layer is a sound decision.  Yes, I get that the current
code base is not in any optimal shape to do much with (the tests are
laughable, the architecture isn't akin to Symfony or Laravel or other
proper frameworks, etc.) but I will argue every day and twice on Sunday
that an incremental approach from the existing API has less chance of failure
than a clean start.

**Pull request closed without merging**
